export const APP_VERSION = '0.5.0';

// Music
export const allNotes = [
    "c",
    "c#",
    "d",
    "d#",
    "e",
    "f",
    "f#",
    "g",
    "g#",
    "a",
    "a#",
    "b",
];

export const allNotesEnh = [
    "c",
    "db",
    "d",
    "eb",
    "fb",
    "f",
    "gb",
    "g",
    "ab",
    "a",
    "bb",
    "cb",
];

export const COLOURS_MERGE = ['#F4D03F', '#b3e5fc', '#bdbdbd'];

export const COLOURS = {
    "1P": '#ffee58',
    "2m": '#b3e5fc',
    "2M": '#87CEFA',
    "2A": '#87CEFA',
    "3m": '#ffcc80',
    "3M": '#ffa726',
    "4P": '#a5d6a7',
    "4A": '#66bb6a',
    "5d": '#e57373',
    "5P": '#FF4136',
    "5A": '#f44336',
    "6m": '#f8bbd0',
    "6M": '#f48fb1',
    "7d": '#e0e0e0',
    "7m": '#bdbdbd',
    "7M": '#9e9e9e'
};

export const allIntervals = ["1P", "2m", "2M", "3m", "3M", "4P", "5d", "5P", "6m", "6M", "7m", "7M"];

// Fretboard
export const Tunings = {
    bass4: {
        standard: ["e1", "a1", "d2", "g2", "b2", "e3"],
    },
    guitar6: {
        standard: ["e2", "a2", "d3", "g3", "b3", "e4"],
        E_4ths: ["e2", "a2", "d3", "g3", "c4", "f4"],
        Drop_D: ["d2", "a2", "d3", "g3", "b3", "e4"],
        G_open: ["d2", "g2", "d3", "g3", "b3", "d4"],
        DADGAD: ["d2", "a2", "d3", "g3", "a3", "d4"],
    },
    guitar7: {
        standard: ["b2", "e2", "a2", "d3", "g3", "b3", "e4"],
        E_4ths: ["b2", "e2", "a2", "d3", "g3", "c3", "f4"],
    },
};

// filtered from Scale.names()...
export const allScales = [
    "major",
    "dorian",
    "phrygian",
    "lydian",
    "mixolydian",
    "aeolian",
    "locrian",
    "harmonic minor",
    "locrian 6",
    "augmented",
    "dorian #4",
    "phrygian dominant",
    "lydian #9",
    "diminished",
    "melodic minor",
    "dorian b2",
    "lydian augmented",
    "lydian dominant",
    "mixolydian b6",
    "locrian #2",
    "altered",
    "major pentatonic",
    "ionian pentatonic",
    "minor six pentatonic",
    "lydian pentatonic",
    "mixolydian pentatonic",
    "minor pentatonic",
    "locrian pentatonic",
    "neopolitan major pentatonic",
    "flat three pentatonic",
    "flat six pentatonic",
    "whole tone pentatonic",
    "lydian #5P pentatonic",
    "lydian dominant pentatonic",
    "minor #7M pentatonic",
    "super locrian pentatonic",
    "major blues",
    "minor blues",
    "composite blues",
    "bebop",
    "bebop minor",
    "bebop major",
    "bebop locrian",
    "minor bebop",
    "minor hexatonic",
    "mystery #1",
    "egyptian",
    "six tone symmetric",
    "whole tone",
    "leading whole tone",
    "locrian major",
    "double harmonic lydian",
    "ultralocrian",
    "augmented heptatonic",
    "lydian diminished",
    "lydian minor",
    "neopolitan major",
    "harmonic major",
    "double harmonic major",
    "oriental",
    "flamenco",
    "persian",
    "enigmatic",
    "major augmented",
    "spanish heptatonic",
    "minor six diminished",
    "half-whole diminished",
    "chromatic"
  ];